# Generated by Django 6.0.3 on 2026-04-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='fine_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
